language: node_js
node_js:
  - "9"

script: yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: build
  repo: lrrfantasy/lrrfantasy.github.io
  target-branch: master
  on:
    branch: master
